################################################################################
#        Copyright (C) 2020        Sebastian Francisco Colomar Bauza           #
#        Copyright (C) 2020        Alejandro Colomar Andr√©s                    #
#        SPDX-License-Identifier:  GPL-2.0-only                                #
################################################################################

configs:
    named:
        file: /run/configs/etc/bind/named.conf

secrets:
    forward:
        file: /run/secrets/var/bind/master/alejandro-colomar.es
    reverse:
        file: /run/secrets/var/bind/master/10.168

services:
    dns:
        configs:
        -
            mode: 0440
            source: named
            target: /etc/bind/named.conf
        deploy:
            mode: global
        image: "alejandrocolomar/bind:1.0.4_amd64"
        ports:
        -   "53:53/udp"
        secrets:
        -
            mode: 0440
            source: forward
            target: var/bind/master/alejandro-colomar.es
        -
            mode: 0440
            source: reverse
            target: var/bind/master/10.168

version: "3.8"

################################################################################
#sudo docker swarm init                                                        ;
#sudo docker stack deploy -c etc/docker/swarm/docker-compose_amd64.yaml web    ;
#sudo docker stack rm web                                                      ;
################################################################################
